apiVersion: v1
kind: Secret
metadata:
  name: invoice-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://aansarana786:Aansa.123@invoice.oyi6xla.mongodb.net/?appName=invoice"

  JWT_SECRET: "umHmxnwAiamERHIAbVX5nlsybmFRwTAbhY6qb8bSJ8A"