apiVersion: v1
kind: Service

metadata:
  name: invoice-service
  labels:
    app: invoice-api
spec:
  selector:
    app: invoice-api

  ports:
    - name: metrics
      port: 3002
      targetPort: 3002

  type: NodePort