apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: invoice-argocd
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:Aansa-123/GitOps-microservices.git
    targetRevision: dev
    path: invoice-api-k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true