apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-api
spec:
  selector:
    app: payment-api

  ports:
    - name: metrics
      port: 3500
      targetPort: 3500

  type: NodePort