apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-api
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: payment-api

  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s