apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://aansarana786_db_user:3ZjqfR09BtvOfE9Q@payment.4qabtct.mongodb.net/?appName=payment"

  JWT_SECRET: "6CuBxiKHF3rGbnnjg4IXp6yfnHUanHdPRkeiASaEhIS"