apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:Aansa.123@postgres-service:5432/userdb?schema=public"
  JWT_SECRET: "6CuBxiKHF3rGbnnjg4IXp6yfnHUanHdPRkeiASaEhIS"
  JWT_EXPIRES_IN: "7d"